version: "3.9"

services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: generator
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:8080:8080"
    restart: "on-failure"
    volumes:
      - ./app:/usr/src/sulu
